### ISSUE TITLE
Unable to import grabcut installed through pip

### ISSUE THREAD

**Issue by zaryabmakram** [luiscarlosgph/grabcut#2]
I am having issues importing the package that has been installed through pip using `pip install grabcut`. 

Following is the error log on running the import command for the package `import grabcut` : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\DELL\.conda\envs\grabcut\lib\site-packages\grabcut\__init__.py", line 1, in <module>
    from grabcut.grabcut import GrabCut
ModuleNotFoundError: No module named 'grabcut.grabcut'
```

The environment specifications are as follows: 
```
# Name                                  Version     
aom                                      3.4.0       
boost                                   1.73.0      
bzip2                                   1.0.8       
ca-certificates                         2022.07.19  
certifi                                 2022.6.15   
expat                                   2.4.8       
ffmpeg                                  4.4.2       
font-ttf-dejavu-sans-mono               2.37        
font-ttf-inconsolata                    2.001       
font-ttf-source-code-pro                2.030       
font-ttf-ubuntu                         0.83        
fontconfig                              2.14.0      
fonts-anaconda                          1           
fonts-conda-ecosystem                   1           
freeglut                                3.2.2       
freetype                                2.10.4      
gettext                                 0.19.8.1    
glib                                    2.72.1      
glib-tools                              2.72.1      
grabcut                                 0.5.0       
gst-plugins-base                        1.20.3      
gstreamer                               1.20.3      
icu                                     70.1        
intel-openmp                            2022.0.0    
jasper                                  2.0.33      
jpeg                                    9e          
krb5                                    1.19.3      
lerc                                    3.0         
libblas                                 3.9.0       
libboost                                1.73.0      
libcblas                                3.9.0       
libclang                                14.0.6      
libclang13                              14.0.6      
libdeflate                              1.8         
libffi                                  3.4.2       
libglib                                 2.72.1      
libiconv                                1.16        
liblapack                               3.9.0       
liblapacke                              3.9.0       
libogg                                  1.3.5       
libopencv                               4.6.0       
libpng                                  1.6.37      
libprotobuf                             3.20.1      
libtiff                                 4.4.0       
libvorbis                               1.3.7       
libwebp-base                            1.2.4       
libxml2                                 2.9.14      
libzlib                                 1.2.12      
lz4-c                                   1.9.3       
mkl                                     2022.1.0    
numpy                                   1.23.2      
opencv                                  4.6.0       
openh264                                2.3.0       
openssl                                 1.1.1q      
pcre                                    8.45        
pip                                     22.1.2      
py-boost                                1.73.0      
py-opencv                               4.6.0       
python                                  3.8.13      
python_abi                              3.8         
qt-main                                 5.15.4      
setuptools                              61.2.0      
sqlite                                  3.39.2      
svt-av1                                 1.2.0       
tbb                                     2021.5.0    
ucrt                                    10.0.20348.0
vc                                      14.2        
vs2015_runtime                          14.29.30037 
wheel                                   0.37.1      
wincertstore                            0.2         
x264                                    1!164.3095  
x265                                    3.5         
xz                                      5.2.5       
zlib                                    1.2.12      
zstd                                    1.5.2       
```

**Comment by luiscarlosgph** [comment]
Hi @zaryabmakram,

Great that you are planning to use this package. It looks like you have not installed the package correctly. Try to run a Docker container and install it following the instructions in the README.

Kind regards,
Luis.
